artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1poseh794R4-gQMhhnsFlHGmdfqJ6SIL0/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/dataset

data_loader:
  root_dir: artifacts/data_ingestion/dataset

model_training:
  root_dir: artifacts/results

model_evaluation:
  root_dir: Model

prediction:
  model_path: Model/best_model.dill