stages:
  data_ingestion:
    cmd: python src/chestCancerClassification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/chestCancerClassification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion


  prepare_base_model:
    cmd: python src/chestCancerClassification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/chestCancerClassification/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/base_models


  training:
    cmd: python src/chestCancerClassification/pipeline/stage_03_model_training.py
    deps:
      - src/chestCancerClassification/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5
