BATCH_SIZE: 16
CLASSES: 4
LEARNING_RATE: 0.001
AUGMENTATION: True

CNN:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3]
  BATCH_SIZE: 32
  EPOCHS: 100
  CLASSES: 4
  LEARNING_RATE: 0.001

VGG16:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
  BATCH_SIZE: 16
  INCLUDE_TOP: False
  EPOCHS: 100
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.001

VGG19:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # as per VGG 19 model
  BATCH_SIZE: 16
  INCLUDE_TOP: False
  EPOCHS: 100
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.001

RESNET:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # as per Resnet model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 100
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

MOBILENET:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # as per MOBILENET model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 100
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

MOBILENETV2:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # as per MOBILENETV2 model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 100
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

INCEPTIONV3:
  AUGMENTATION: True
  IMAGE_SIZE: [299, 299, 3] # as per InceptionV3 model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 100
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

Xception:
  AUGMENTATION: True
  IMAGE_SIZE: [299, 299, 3] # as per Xception model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 100
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

