stages:
  data_ingestion:
    cmd: python src/kidneyDiseaseClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/kidneyDiseaseClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image

  prepare_base_model:
    cmd: python src/kidneyDiseaseClassifier/pipeline/stage_02_model_building.py
    deps:
      - src/kidneyDiseaseClassifier/pipeline/stage_02_model_building.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/kidneyDiseaseClassifier/pipeline/stage_03_model_training.py
    deps:
      - src/kidneyDiseaseClassifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/kidneyDiseaseClassifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/kidneyDiseaseClassifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false